CREATE TYPE ESTADO_CIVIL AS ENUM('SOLTEIRO_A', 'CASADO_A', 'UNIAO_ESTAVEL', 'SEPARADO_A', 'DIVORCIADO_A', 'VIUVO_A');

CREATE TYPE ESCOLARIDADE AS ENUM('ANALFABETO', 'ENSINO_FUNDAMENTAL_INCOMPLETO', 'ENSINO_FUNDAMENTAL_COMPLETO', 'ENSINO_MEDIO_INCOMPLETO', 'ENSINO_MEDIO_COMPLETO', 'ENSINO_SUPERIOR_INCOMPLETO', 'ENSINO_SUPERIOR_COMPLETO');

CREATE TYPE GRAU_PARENTESCO AS ENUM('ESPOSO_A', 'PAI', 'MAE', 'AVOS', 'FILHOS_AS', 'IRMAO_A', 'TIO_A', 'SOBRINHO_A', 'PRIMO_A', 'SOGRO_A', 'ENTEADO_A', 'OUTROS');

CREATE TYPE RESIDENCIA AS ENUM('PROPRIA', 'ALUGADA', 'AREA_DE_INVASAO', 'CEDIDA');

CREATE TYPE VIOLENCIA AS ENUM('NAO', 'FISICA', 'VERBAL', 'PSICOLOGICA', 'SEXUAL', 'PATRIMONIAL', 'OUTROS');

CREATE TYPE ATIVIDADE_LAZER AS ENUM('NAO', 'MANUAIS', 'SOCIAIS', 'FISICAS_ESPORTIVAS', 'CULTURAIS', 'OUTROS');

CREATE TYPE QUALIDADE_VIDA AS ENUM('EXCELENTE', 'BOA', 'REGULAR', 'RUIM');

CREATE TYPE VACINA AS ENUM('SIM', 'NAO', 'NAO_SABE');

create table FormSocial(
	ID SERIAL primary key,
	NOME VARCHAR(100) not null,
	DATAENTREVISTA TIMESTAMP,
	DATANASCIMENTO DATE,
	IDADE INTEGER not null,
	TELEFONE VARCHAR(15) not null,
	EMAIL VARCHAR(50) not null,
	FUNCAO_EXERC VARCHAR(30) not null,
	TEMPO_FUNCAO_EXERC VARCHAR(10) not null,
	ESTADO_CIVIL ESTADO_CIVIL not null,
	ESCOLARIDADE ESCOLARIDADE not null,
	NUMERO_PESSOAS_FAM INTEGER not null,
	GRAU_PARENTESCO GRAU_PARENTECO not null,
	RESIDENCIA RESIDENCIA not null,
	BENEFICIO BOOLEAN not null,
	BENEFICIO_DESCRICAO VARCHAR(20),
	PROGRAMA_SOCIAL BOOLEAN not null,
	PROGRAMA_SOCIAL_DESCRICAO VARCHAR(20),
	DOENCA_CRONICA BOOLEAN not null,
	DOENCA_CRONICA_DESCRICAO VARCHAR(30),
	DEFICIENTE_FAMILIA BOOLEAN not null,
	DEFICIENTE_FAMILIA_DESCRICAO VARCHAR(50),
	ACOMP_MEDICO BOOLEAN not null,
	ACOMP_MEDICO_DESCRICAO VARCHAR(20),
	SUICIDIO_FAMILIA BOOLEAN not null,
	SUICIDIO_GRAU_PARENTECO GRAU_PARENTESCO,
	VIOLENCIA VIOLENCIA,
	VIOLENCIA_DESCRICAO VARCHAR(30),
	PSICOATIVOS BOOLEAN not null,
	PSICOATIVOS_DESCRICAO VARCHAR(30),
	C0NFLITO_FAMILIAR BOOLEAN not null,
	ATIVADE_LAZER ATIVIDADE_LAZER,
	ATIVIDADE_LAZER_DESCRICAO VARCHAR(30),
	ATIVIDADE_FISICA BOOLEAN not null,
	ATIVIDADE_FISICA_DESCRICAO VARCHAR(20),
	QUALIDADE_VIDA QUALIDADE_VIDA,
	VACINA VACINA,

)